spring.application.name=ibm-bank-challenge
spring.jackson.time-zone=UTC
spring.profiles.active=@spring.profile@
spring.jpa.open-in-view=true

# Comma separated list of origins allowed by CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200,https://front-ibm-bank-self.vercel.app,https://ibm-bank-challenge.vercel.app,https://ibm-bank-front.onrender.com}

management.endpoints.web.exposure.include=health
