spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/ibm-bank-challenge}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.flyway.enabled=false
